SELECT
    COUNT(DISTINCT "MATCH.ID")  "NUM.MATCHES",
    AVG("DURATION.MIN")  "AVG.MATCH.DURATION"
FROM DOTA2_DATA;


SELECT DISTINCT
    "PLAYER.SLOT",
    MIN(KILLS)  "MIN.KILLS",
    MAX(KILLS)  "MAX.KILLS",
    AVG("HERO.DMG")  "AVG.HERO.DMG"
FROM DOTA2_DATA
WHERE WIN = TRUE
GROUP BY "PLAYER.SLOT";


SELECT DISTINCT
    "MATCH.ID",
    SUM("LAST.HITS")  "MATCH.LAST.HITS"
    SUM("DENIES")  "MATCH.DENIES",
FROM DOTA2_DATA
WHERE "ISRADIANT" = TRUE
AND "FIRST.BLOOD" = TRUE;


SELECT DISTINCT
    AVG("GOLD.P.MIN")  "AVG.GPM",
    AVG("XP.P.MIN")  "AVG.XPM"
    SUM("HERO.DMG")  "TOTAL.HERO.DMG"
FROM DOTA2_DATA  TA1
WHERE "MATCH.KILLS" >= 25
AND "MATCH.ID" IN (
    SELECT "MATCH.ID"
    FROM DOTA2_DATA  TA2
    WHERE "GOLD.P.MIN" >= 500
    AND "RUNES" BETWEEN 2 AND 5);
